### PR TITLE
added MichaelH.txt file

### PR DESCRIPTION
**Pull request by mhaytest**
needed addtion

### CODE REVIEW

**Comment by PeterBell** [comment]
LGTM 👍

**Comment by PeterBell** [comment]
excited-kid

**Comment by PeterBell** [comment]
Hey @jjlorbec what do *you* think of this? Should we 🚢 it?!

**Comment by tylerh3** [comment]
We should NOT ship this.

**Comment by PeterBell** [comment]
hey @peterbell any comments?

**Comment by tylerh3** [comment]
There is a critical flaw in this code!!

**Comment by githubteacher** [comment]
Sorry - no 😦

**Pull request closed without merging**
