### PR TITLE
Added Glenn to the project

### PR DESCRIPTION
**Pull request by GlennWienke**
Glenn needs to be on this project.

### CODE REVIEW

**Comment by PeterBell** [comment]
LGTM 👍

**Comment by PeterBell** [comment]
I think we should 🚢 it

**Comment by tykinteractive** [comment]
:100:

**Comment by PeterBell** [comment]
harry-potter-congrats

**Comment by PeterBell** [comment]
Not bad, but could you add some more test coverage

**Comment by PeterBell** [comment]
@brntbeer what do you think of this? (class)

**Pull request merged**
